import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 20,
  },
  compassContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 20,
    height: 320,
  },
  compassBackground: {
    alignItems: "center",
    justifyContent: "center",
    width: 280,
    height: 280,
    borderRadius: 140,
    borderWidth: 3,
    borderColor: "rgba(255, 215, 0, 0.3)",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  compassOuterRing: {
    width: 260,
    height: 260,
    borderRadius: 130,
    borderWidth: 10,
    borderColor: "rgba(74, 144, 226, 0.3)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  compassInnerRing: {
    width: 240,
    height: 240,
    borderRadius: 120,
    borderWidth: 2,
    borderColor: "rgba(74, 144, 226, 0.7)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 10,
  },
  compassRose: {
    position: "absolute",
    width: 280,
    height: 280,
    alignItems: "center",
    justifyContent: "center",
  },
  cardinalDirection: {
    position: "absolute",
    fontSize: 18,
    fontWeight: "bold",
    color: "#4A90E2",
    textShadowColor: "rgba(74, 144, 226, 0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  degreeMarker: {
    position: "absolute",
    width: 2,
    backgroundColor: "rgba(74, 144, 226, 0.5)",
  },
  qiblaNeedle: {
    position: "absolute",
    width: 50,
    height: 140,
    alignItems: "center",
    justifyContent: "center",
  },
  needleGradient: {
    width: 50,
    height: 140,
    alignItems: "center",
    justifyContent: "flex-start",
    borderRadius: 25,
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 8,
  },
  makkahIconContainer: {
    position: "absolute",
    top: -140,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 15,
  },
  makkahIconBackground: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#FFD700",
    backgroundColor: "rgba(255, 215, 0, 0.2)",
  },
  makkahIcon: {
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 8,
  },
  centerDot: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 4,
    borderColor: "#4A90E2",
    backgroundColor: "#FFD700",
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  directionText: {
    marginTop: 20,
    fontSize: 26,
    fontWeight: "bold",
    color: "#4A90E2",
    textShadowColor: "rgba(74, 144, 226, 0.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  separator: {
    marginVertical: 20,
    height: 2,
    width: "80%",
    backgroundColor: "rgba(74, 144, 226, 0.2)",
  },
  errorContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 20,
    color: "#FF6B6B",
  },
  calibrationContainer: {
    alignItems: "center",
    justifyContent: "center",
    height: 300,
  },
  calibrationAnimation: {
    marginBottom: 20,
  },
  calibrationText: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    color: "#4A90E2",
  },
  calibrationSubText: {
    fontSize: 15,
    textAlign: "center",
    marginTop: 10,
    opacity: 0.8,
    color: "#666",
  },
  infoText: {
    fontSize: 15,
    textAlign: "center",
    marginTop: 10,
    opacity: 0.8,
    color: "#666",
  },
  button: {
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: "#4A90E2",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  recalibrateButton: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 15,
    padding: 10,
    borderRadius: 20,
    backgroundColor: "rgba(74, 144, 226, 0.1)",
  },
  recalibrateText: {
    marginLeft: 8,
    fontSize: 15,
    color: "#4A90E2",
  },
  detailsToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    padding: 8,
    borderRadius: 15,
    backgroundColor: "rgba(74, 144, 226, 0.1)",
  },
  detailsToggleText: {
    fontSize: 15,
    marginRight: 8,
    color: "#4A90E2",
  },
  detailsPanel: {
    width: width - 40,
    overflow: "hidden",
    borderRadius: 15,
    marginTop: 15,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  blurContainer: {
    flex: 1,
    padding: 20,
    borderRadius: 15,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    backgroundColor: "rgba(74, 144, 226, 0.1)",
    padding: 12,
    borderRadius: 10,
  },
  detailText: {
    marginLeft: 12,
    fontSize: 15,
    color: "#4A90E2",
  },
  accuracyIndicator: {
    position: "absolute",
    top: -35,
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  accuracyText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
});